Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import skunk
exmol.lime_explain(space, descriptor_type='ECFP')
svg = exmol.plot_descriptors(space, return_svg=True)
skunk.display(svg)
exmol.plot_utils.similarity_map_using_tstats(space[0])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [9][0m, in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      2[0m exmol[38;5;241m.[39mlime_explain(space, descriptor_type[38;5;241m=[39m[38;5;124m'[39m[38;5;124mECFP[39m[38;5;124m'[39m)
[1;32m      3[0m svg [38;5;241m=[39m exmol[38;5;241m.[39mplot_descriptors(space, return_svg[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[0;32m----> 4[0m [43mskunk[49m[38;5;241;43m.[39;49m[43mdisplay[49m[43m([49m[43msvg[49m[43m)[49m
[1;32m      5[0m exmol[38;5;241m.[39mplot_utils[38;5;241m.[39msimilarity_map_using_tstats(space[[38;5;241m0[39m])

File [0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/skunk/__init__.py:64[0m, in [0;36mdisplay[0;34m(svg)[0m
[1;32m     62[0m [38;5;28;01mimport[39;00m [38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdisplay[39;00m [38;5;28;01mas[39;00m [38;5;21;01mdisplay[39;00m
[1;32m     63[0m [38;5;28;01mimport[39;00m [38;5;21;01mbase64[39;00m
[0;32m---> 64[0m data [38;5;241m=[39m base64[38;5;241m.[39mb64encode([43msvg[49m[38;5;241;43m.[39;49m[43mencode[49m([38;5;124m'[39m[38;5;124mutf8[39m[38;5;124m'[39m))
[1;32m     65[0m display[38;5;241m.[39mdisplay(display[38;5;241m.[39mHTML(
[1;32m     66[0m     [38;5;124m'[39m[38;5;124m<img src=data:image/svg+xml;base64,[39m[38;5;124m'[39m [38;5;241m+[39m data[38;5;241m.[39mdecode() [38;5;241m+[39m [38;5;124m'[39m[38;5;124m>[39m[38;5;124m'[39m))

[0;31mAttributeError[0m: 'NoneType' object has no attribute 'encode'
AttributeError: 'NoneType' object has no attribute 'encode'

